# Generated by Django 3.2.25 on 2026-02-27 04:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='邮件主题')),
                ('content', models.TextField(verbose_name='邮件内容')),
                ('content_html', models.TextField(blank=True, verbose_name='HTML内容')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('scheduled', '定时发送'), ('sent', '已发送')], default='draft', max_length=20, verbose_name='状态')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='定时发送时间')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('recipient_count', models.PositiveIntegerField(default=0, verbose_name='接收者数量')),
                ('open_count', models.PositiveIntegerField(default=0, verbose_name='打开数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('related_posts', models.ManyToManyField(blank=True, to='blog.Post', verbose_name='关联文章')),
            ],
            options={
                'verbose_name': '新闻通讯',
                'verbose_name_plural': '新闻通讯',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱地址')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='昵称')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='验证令牌')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('subscribe_date', models.DateTimeField(auto_now_add=True, verbose_name='订阅时间')),
                ('unsubscribe_date', models.DateTimeField(blank=True, null=True, verbose_name='退订时间')),
                ('last_sent_date', models.DateTimeField(blank=True, null=True, verbose_name='上次发送时间')),
            ],
            options={
                'verbose_name': '订阅者',
                'verbose_name_plural': '订阅者',
                'ordering': ['-subscribe_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('opened', models.BooleanField(default=False, verbose_name='是否打开')),
                ('opened_date', models.DateTimeField(blank=True, null=True, verbose_name='打开时间')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='newsletter.newsletter', verbose_name='新闻通讯')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='newsletter.subscriber', verbose_name='订阅者')),
            ],
            options={
                'verbose_name': '发送日志',
                'verbose_name_plural': '发送日志',
                'ordering': ['-sent_date'],
            },
        ),
    ]
